<div class="form-horizontal">
    <div class="form-group">
        <div class="btn-group">
            <a href="<?= $this->url('esquema',array('action'=>'nuevo'))?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> NUEVO</a>
            <a href="#" class="btn btn-warning"><i class="glyphicon glyphicon-th"></i> GENERAR REPORTE</a>
        </div>
    </div>
    <div class="form-group">
        <form class="col-lg-7">
            <div class="input-group">
                <div class="input-group-addon">Nombre de Asesor</div>
                <input type="text" name="q" class="form-control"/>
                <div class="input-group-btn">
                    <button class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">Resultados</h4>
    </div>
    <table class="panel-body table table-bordered table-hover">
        <thead>
        <th>#</th>
        <th>CÓDIGO</th>
        <th>APELLIDOS</th>
        <th>NOMBRES</th>
        <th>ASESORADOS</th>
        <th></th>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>