<form class="form-horizontal" role="form" method="post">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#asesor" data-toggle="tab" >Datos de Docente</a></li>
        <li><a href="#asesorados" data-toggle="tab">Asesorados</a></li>
    </ul>
    <div class="tab-content">
        <br>
        <div class="tab-pane active" id="asesor">
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="col-lg-2 control-label">Código</label>
                    <div class="col-lg-3">
                        <div class="input-group">
                            <input type="text" class="form-control" />
                            <div class="input-group-btn">
                                <a href="#" class="btn btn-default" ><i class="glyphicon glyphicon-search"></i></a>
                            </div>
                        </div>
                    </div>
                    <label class="col-lg-2 control-label">DNI</label>
                    <div class="col-lg-3">
                        <input type="tex" readonly class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="col-lg-2 control-label">Nombres</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" name="nombres" readonly>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="col-lg-2 control-label">Ap. Paterno</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" name="ape_pat" readonly>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="col-lg-2 control-label">Ap. Materno</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" name="ape_mat" readonly>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group pull-right">
                    <a href="#asesorados" data-toggle="tab" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> AGREGAR ASESORADO</a>
                    <button class="btn btn-primary"><i class="glyphicon glyphicon-saved"></i> GUARDAR</button>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="asesorados">
            <div class="col-lg-12">
                <div class="form-group">
                    <button class="btn btn-success"><i class="glyphicon glyphicon-plus"></i></button>
                    <button class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i></button>
                </div>
            </div>
            <div class="col-lg-12">
                <table class="row table table-bordered table-hover">
                    <thead>
                        <th>#</th>
                        <th>Alumno</th>
                        <th>Titulo Tesis</th>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>