<div class="page-header">
    <h3>Programaciones</h3>
</div>
<div class="form-horizontal">
    <div class="control-group">
        <div class="btn-group">
            <a href="<?= $this->url('programacion', array('action'=>'nuevo'))?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> NUEVO</a>
            <a class="btn btn-warning"><i class="glyphicon glyphicon-th"></i> GENERAR REPORTES</a>
        </div>
    </div>
</div>
<div class="form-horizontal">
    <form method="post">
        <div class="span6">
            <div class="control-group">
                <div class="control-label">Fecha Programada</div>
                <div class="controls">
                    <input type="date" class="form-control"/>
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                <div class="control-label">Fecha Término</div>
                <div class="controls">
                    <input type="date" class="form-control"/>
                    <button class="btn btn-primary"><i class="icon-search"></i> BUSCAR</button>
                </div>
            </div>
        </div>
    </form>
</div>
<table class="table table-bordered table-hover">
    <thead>
    <th>CoÓDIGO</th>
    <th>ASESORIA</th>
    <th>EVALUACIÓN</th>
    <th>FECHA</th>
    <th>HORA</th>
    <th>FECHA REG.</th>
    <th>EDITAR</th>
    </thead>
    <tbody>
    <?php foreach ($programacion as $pro):?>
        <tr>
            <td><?=$pro['prog_id']?></td>
            <td><?=$pro['asesoria_id']?></td>
            <td><?=$pro['eva_id']?></td>
            <td><?=$pro['prog_fecha']?></td>
            <td><?=$pro['prog_hora']?></td>
            <td><?=$pro['prog_f_reg']?></td>
            <td>
                <a href="<?=$this->url('programacion',['action' => 'editar', 'key' => $pro['prog_id']])?>" class="btn btn-info btn-inverse"><i class="icon-edit"></i></a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
    </tbody>
</table>