<div class="page-header">
    <h3>Nueva Programación</h3>
</div>
<form class="form-horizontal">
    <div class="control-group">
        <label class="control-label">Datos de Asesor</label>
        <div class="controls">
            <input type="text" class="form-control" readonly/>
            <input type="text" class="form-control span8" readonly />
            <a href="#" class="btn btn-default"><i class="icon-search"></i></a>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Alumno</label>
        <div class="controls">
            <input type="text" class="form-control" readonly />
            <input type="text" class="form-control span8" readonly />
            <a href="#" class="btn btn-default"><i class="icon-search"></i></a>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Tesis</label>
        <div class="controls">
            <input type="text" readonly class="form-control span11">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Fecha</label>
        <div class="controls">
            <input type="date" class="form-control">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Hora</label>
        <div class="controls">
            <input type="time" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <div class="pull-right">
            <button class="btn btn-primary"><i class="glyphicon glyphicon-saved"></i> GUARDAR</button>
        </div>
    </div>
</form>