<style>
    body,*{
        margin: 0px;
        padding: 0px;
    }
    .bg-metro{
        position: fixed;
        width: 100%;
        height: 100%;
        background: url(<?=$this->basePath('img/bg.png')?>);
    }
    .bg-metro h2{
        position: fixed;
        left: 30%;
        width: 40%;
        top: 18%;
        font-size: 22px;
        color: #ffffff;
        font-stretch: expanded;
    }
    .bg-metro form{
        position: fixed;
        left: 30%;
        width: 40%;
        top: 25%;
        background: #fefefe;
        padding: 20px;
        box-shadow: 3px 4px rgba(10,10,10,0.2);
    }
</style>
<div class="bg-metro">
    <div class="container">
        <h2>SISTEMA CONTROL DE TESIS</h2>
        <form class="form-horizontal" method="post" >
            <div class="row">
                <div class="col-lg-4">
                    <img class="img img-responsive" src="<?=$this->basePath('img/user.png')?>">
                </div>
                <div class="col-lg-8">
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Usuario</label>
                        <div class="col-lg-8">
                            <input type="text" class="form-control" name="username" placeholder="Ingrese nombre de usuario" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label">Contraseña</label>
                        <div class="col-lg-8">
                            <input type="password" class="form-control" name="password" placeholder="Ingrese su contraseña" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12 pull-right">
                            <a class="btn btn-link"><i class="glyphicon glyphicon-circle-o"></i> ¿Olvidaste Contraseña?</a>
                            <button class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i> INICIAR</button>
                        </div>

                    </div>
                </div>
            </div>
        </form>
    </div>
</div>