<div class="row-fluid">
    <div class="span12">
        <div class="form-group">
            <div class="btn-group">
                <a href="<?= $this->url('esquema',array('action'=>'nuevo'))?>" class="btn btn-success"><i class="icon-plus"></i> NUEVO</a>
                <a href="#" class="btn btn-warning"><i class="icon-th"></i> GENERAR REPORTE</a>
            </div>
        </div>
        <br>
    </div>
</div>
<div class="row-fluid">

    <div class="form-horizontal">
        <fieldset>
            <div class="span5">
                <div class="form-group">
                    <label class="control-label">Filtro</label>
                    <div class="controls">
                        <select class="form-control">
                            <option value="tes_titulo"> Título de Tesis</option>
                            <option value="tes_titulo"> Estudiante</option>
                            <option value="tes_titulo"> N° de Tramite</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="span7">
                <form>
                    <div class="input-prepend input-append">
                        <input type="text" name="q" class="form-control"/>
                        <button class="btn btn-default"><i class="icon-search"></i></button>
                    </div>
                </form>
            </div>
        </fieldset>
    </div>

    <?=\Application\TnqSoft\Functions::getPaginacion()?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">Resultados de equemas de tesis</h4>
        </div>
        <table class="panel-body table table-bordered table-hover">
            <thead>
            <th>N° TRAMITE</th>
            <th>TITULO DE TESIS</th>
            <th>ESTUDIANTE</th>
            <th>ESTADO</th>
            <th></th>
            </thead>
            <tbody>
            <?php foreach ($esquemas as $esq):?>
            <tr>
                <td><?=$esq->tram_id?></td>
                <td><?=$esq->titulo?></td>
                <td><?=$esq->estudiante?></td>
                <td><?=$esq->estado?></td>
                <td>
                    <a href="<?=$this->url('esquema',['action' => 'editar', 'id' => $esq->tram_id])?>" class="btn btn-info btn-inverse"><i class="icon-edit"></i></a>
                </td>
            </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>