<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="<?=$this->basePath()?>">Inicio</a>
        <i class="icon-angle-right"></i>
    </li>
    <li>
        <a href="<?=$this->url('esquema')?>">Esquema</a>
        <i class="icon-angle-right"></i>
    </li>
    <li>Nuevo Esquema</li>
</ul>
<div  class="row-fluid form-horizontal">
    <div class="box span12">
        <div class="box-header-tabs">
            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a href="#estudiante" data-toggle="tab"> DATOS DE ESTUDIANTE</a></li>
                <li><a href="#esquema" data-toggle="tab"> DATOS DE ESQUEMA</a></li>
            </ul>
        </div>
        <div class="box-content">
            <form id="nuevoEsquema" class="tab-content clearfix" method="post">
                <div class="tab-pane active" id="estudiante">
                    <div class="span9">
                        <div class="control-group">
                            <label class="control-label">CÓDIGO</label>
                            <div class="controls">
                                <input readonly class="form-control" type="text" name="codigo">
                                <button data-style="modal-lg" data-role="modal-async" data-href="<?=$this->url('estudiante', ['action'=>'buscar'])?>" data-icon="icon-search" data-title="Buscar Estudiante" class="btn btn-default" type="button"><i class="icon-search"></i></button>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">DNI</label>
                            <div class="controls">
                                <input class="form-control" type="text" name="dni" readonly>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">NOMBRES</label>
                            <div class="controls">
                                <input type="text" class="form-control size-y" name="nombres" readonly>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">APELLIDOS</label>
                            <div class="controls">
                                <input type="text" class="form-control size-y" name="apellidos" readonly>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">DIRECCION</label>
                            <div class="controls">
                                <input type="text" class="form-control size-y" name="direccion" readonly>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">FECHA NAC</label>
                            <div class="controls">
                                <input name="fecha_nac" type="date" class="form-control" readonly />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">N° TRAMITE</label>
                            <div class="controls">
                                <div class="input-prepend input-append">
                                    <input readonly type="text" class="form-control" NAME="tramite" />
                                    <button id="btn-buscar-tramite" data-role="modal-async" data-href="<?$this->basePath()?>" data-title="Tramites" data-icon="icon-list-th" class="btn btn-default" type="button"><i class="icon-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane center" id="esquema">
                    <div class="span8">
                        <div class="control-group">
                            <label class="control-label">Titulo de Tesis</label>
                            <div class="controls">
                                <input type="text" class="form-control size-y" placeholder="Ingrese titulo de tesis" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Palabras clave</label>
                            <div class="controls">
                                <textarea class="form-control size-y"></textarea>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Objetivos Principales</label>
                            <div class="controls">
                                <textarea class="cleditor size-y"></textarea>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Objetivos Secundarios</label>
                            <div class="controls">
                                <textarea class="cleditor size-y"></textarea>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">EStado</label>
                            <div class="controls">
                                <input type="text" readonly class="form-control size-y" value="PRESENTADO" />
                            </div>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="btn-group">
                            <a href="#estudiante" data-toggle="tab" class="btn btn-info"><i class="icon-arrow-left"></i> Atras</a>
                            <button class="btn btn-success"><i class="icon-saved"></i> GUARDAR</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="<?=$this->basePath('plugins/estudiante.TnqSoft.js')?>"></script>
<script>
    $('#myTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    })
</script>