<div class="row-fluid">
    <table id="tbTramite" class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th>CODIGO</th>
            <th>CODIGO ESTUDIANTE</th>
            <th>CODIGO PAGINA</th>
            <th>FECHA</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($tramites as $item):?>

            <tr>
                <td><?=$this->escapeHtml($item['tram_id'])?></td>
                <td><?=$this->escapeHtml($item['est_codigo'])?></td>
                <td><?=$this->escapeHtml($item['pag_codigo'])?></td>
                <td><?=$this->escapeHtml($item['tram_fecha_reg'])?></td>
                <td>
                    <button data-role="close-modal" data-action="Tramite.elegir('<?=$item['tram_id']?>')" class="btn btn-primary"><i class="icon-check"></i></button>
                </td>
            </tr>

        <?php endforeach;?>

        </tbody>
    </table>
</div>
