<?php if($estado==false){?>
    <form onsubmit="javascript: void(0);" class="row-fluid form-horizontal" action="<?=$this->url('tramite', ['action'=>'nuevo'])?>" id="frmNuevoTramite" method="post">
        <div class="span8">
            <div class="control-group">
                <label class="control-label">COD. ESTUDIANTE</label>
                <div class="controls">
                    <input name="tramiteID" type="hidden" readonly>
                    <input class="form-control size-y" name="codigo" type="text">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">COD. PAGO</label>
                <div class="controls">
                    <input type="text" class="form-control size-y" name="pag_codigo" >
                </div>
            </div>
            <div class="control-group">
                <p id="alertsMsg"></p>
            </div>
        </div>
        <div class="span4">
            <div class="btn-group">
                <button type="button" onclick="Estudiante.loadInfo()" class="btn btn-success"><i class="icon-ok-sign"></i></button>
                <button onclick="Global.HttpRequest('#frmNuevoTramite')" class="btn btn-primary"><i class="icon-save"></i> GUARDAR</button>
            </div>
        </div>
    </form>
<?php
}else{
?>
<div class="alert alert-<?=$estado?'success':'danger'?>">
    <h3><?=$mensaje?></h3>
</div>
<?php
}
?>
