<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="index.html">Inicio</a>
    </li>
</ul>
<div class="row-fluid">
    <div class="span12">
        <div class="form-group">
            <div class="btn-group">
                <a href="<?= $this->url('tesis',array('action'=>'nuevo'))?>" class="btn btn-success"><i class="icon-plus"></i> NUEVO</a>
                <a href="#" class="btn btn-warning"><i class="icon-th"></i> GENERAR REPORTE</a>
            </div>
        </div>
        <br>
    </div>
</div>
<div class="row-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">LISTA DE TESIS APROBADAS</h2>
        </div>
        <table id="tesis" class="panel-body table table-bordered table-striped table-condensed">
            <thead>
            <th>N° ACTA</th>
            <th>TITULO DE TESIS</th>
            <th>ESTADO DE TESIS</th>
            </thead>
            <tbody>
            <?php foreach ($tesis as $tes):?>
                <tr>
                    <td><?=$tes['acta_id']?></td>
                    <td><?=$tes['titulo_tesis']?></td>
                    <td><?=sprintf("%s %s %s",$tes['eva_descripcion'], $tes['eva_fecha_reg'])?></td>
                    <td><?=$tes['estado_tesis']?></td>
                    <td>
                        <a href="<?=$this->url('tesis',['action' => 'editar', 'key' => $tes['acta_id']])?>" class="btn btn-info btn-inverse"><i class="icon-edit"></i></a>
                    </td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>