<div class="row-fluid">
    <div class="box span12">
        <div class="box-header">
            <div class="control-group">
                <label class="control-label">Buscar</label>
                <div class="controls">
                    <input type="text" class="form-control" name="query" />
                </div>
            </div>
        </div>
    </div>
    <div class="box-content">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>CODIGO</th>
                    <th>DNI</th>
                    <th>NOMBRES Y PELLIDOS</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>