<div class="row-fluid">
    <div class="box span12">
        <div class="box-header">
            <h2>
                <span class="icon-home"></span>
                <span class="break"></span>
                Bienvenido al Sistema Control de Tesis
            </h2>
        </div>
        <div class="box-content">
            <div class="row-fluid">
                <div class="span6">
                    <ul CLASS="dashboard-list">
                        <li style="padding: 3px;" class="red">UNIVERSIDAD SAN PEDRO</li>
                        <li style="padding: 3px;">Curso: <strong>Eletivo II</strong></li>
                        <li style="padding: 3px;">Año: <strong>2016 - II</strong></li>
                        <li style="padding: 3px;" class="red">INTEGRANTES</li>
                        <li style="padding: 3px;"><i class="icon-circle-blank"></i> Laredo Meza Paris</li>
                        <li style="padding: 3px;"><i class="icon-circle-blank"></i> Olano Leon Linkol Alexander</li>
                        <li style="padding: 3px;"><i class="icon-circle-blank"></i> Tume Naquiche Alexander Estevan</li>
                    </ul>
                </div>
                <div class="span6">

                </div>
            </div>
        </div>
    </div>
</div>
