<div class="row-fluid">
    <table id="tbPersona" class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th>CODIGO</th>
            <th>DNI</th>
            <th>NOMBRE</th>
            <th>APELLIDO PATERNO</th>
            <th>APELLIDO MATERNO</th>
            <th>DIRECCION</th>
            <th>TELEFONO</th>
            <th>EMAIL</th>
            <th>FECHA NACIMIENTO</th>
            <th>FECHA REGISTRO</th>

        </tr>
        </thead>
        <tbody>

        <?php foreach ($persona as $item):?>

            <tr>
                <td><?=$this->escapeHtml($item['per_id'])?></td>
                <td><?=$this->escapeHtml($item['per_dni'])?></td>
                <td><?=$this->escapeHtml($item['per_nombre'])?></td>
                <td><?=$this->escapeHtml($item['per_ape_pat'])?></td>
                <td><?=$this->escapeHtml($item['per_ape_mat'])?></td>
                <td><?=$this->escapeHtml($item['per_direccion'])?></td>
                <td><?=$this->escapeHtml($item['per_telefono'])?></td>
                <td><?=$this->escapeHtml($item['per_email'])?></td>
                <td><?=$this->escapeHtml($item['per_fecha_nac'])?></td>
                <td><?=$this->escapeHtml($item['per_fecha_reg'])?></td>
                <td>
                    <button data-role="close-modal" data-action="Persona.elegir('<?=$item['per_id']?>','<?=$item['per_dni']?>','<?=$item['per_nombre']?>','<?=$item['per_ape_pat']?>','<?=$item['per_ape_mat']?>')" class="btn btn-primary"><i class="icon-check"></i></button>
                </td>
            </tr>

        <?php endforeach;?>

        </tbody>
    </table>
</div>
