<div class="page-header">
    <h3>Programaciones</h3>
</div>
<div class="form-horizontal">
    <div class="control-group">
        <div class="btn-group">
            <a href="<?= $this->url('programacion', array('action'=>'nuevo'))?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> NUEVO</a>
            <a class="btn btn-warning"><i class="glyphicon glyphicon-th"></i> GENERAR REPORTES</a>
        </div>
    </div>
</div>
<div class="form-horizontal">
    <form method="post">
        <div class="span6">
            <div class="control-group">
                <div class="control-label">Fecha Inicio</div>
                <div class="controls">
                    <input type="date" class="form-control"/>
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                <div class="control-label">Fecha Término</div>
                <div class="controls">
                    <input type="date" class="form-control"/>
                    <button class="btn btn-primary"><i class="icon-search"></i> BUSCAR</button>
                </div>
            </div>
        </div>
    </form>
</div>
<table class="table table-bordered table-hover">
    <thead>
    <th>#</th>
    <th>Fecha</th>
    <th>Hora</th>
    <th>Detalles</th>
    </thead>
    <tbody>

    </tbody>
</table>