<div class="page-header">
    <h3>Nueva Programación</h3>
</div>
<form class="form-horizontal">
    <div class="form-group">
        <label class="col-lg-2">Datos de Asesor</label>
        <div class="col-lg-2">
            <input type="text" class="form-control" readonly/>
        </div>
        <div class="col-lg-8">
            <div class="input-group">
                <input type="text" class="form-control" readonly />
                <div class="input-group-btn">
                    <a href="#" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Alumno</label>
        <div class="col-lg-2">
            <input type="text" class="form-control" readonly />
        </div>
        <div class="col-lg-8">
            <div class="input-group">
                <input type="text" class="form-control" readonly />
                <div class="input-group-btn">
                    <a href="#" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Tesis</label>
        <div class="col-lg-10">
            <input type="text" readonly class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Fecha</label>
        <div class="col-lg-4">
            <input type="date" class="form-control">
        </div>
        <label class="col-lg-2 control-label">Hora</label>
        <div class="col-lg-4">
            <input type="time" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <div class="pull-right">
            <button class="btn btn-primary"><i class="glyphicon glyphicon-saved"></i> GUARDAR</button>
        </div>
    </div>
</form>