<div class="row-fluid">
    <table id="tbCargo" class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th>CODIGO</th>
            <th>NOMBRE</th>
            <th>DESCRIPCION</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($cargo as $item):?>

            <tr>
                <td><?=$this->escapeHtml($item['car_id'])?></td>
                <td><?=$this->escapeHtml($item['car_nombre'])?></td>
                <td><?=$this->escapeHtml($item['car_descripcion'])?></td>
                <td>
                    <button data-role="close-modal" data-action="Cargo.elegir('<?=$item['car_id']?>','<?=$item['car_nombre']?>')" class="btn btn-primary"><i class="icon-check"></i></button>
                </td>
            </tr>

        <?php endforeach;?>

        </tbody>
    </table>
</div>
