<div class="form-horizontal">
    <div class="form-group">
        <div class="btn-group">
            <a href="<?= $this->url('esquema',array('action'=>'nuevo'))?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> NUEVO</a>
            <a href="#" class="btn btn-warning"><i class="glyphicon glyphicon-th"></i> GENERAR REPORTE</a>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-1 control-label">Filtro</label>
        <div class="col-lg-2">
            <select class="form-control">
                <option value="tes_titulo"> Título de Tesis</option>
                <option value="tes_titulo"> Estudiante</option>
                <option value="tes_titulo"> N° de Tramite</option>
            </select>
        </div>
        <form class="col-lg-7">
            <div class="input-group">
                <input type="text" name="q" class="form-control"/>
                <div class="input-group-btn">
                    <button class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">Resultados de equemas de tesis</h4>
    </div>
    <table class="panel-body table table-bordered table-hover">
        <thead>
        <th>N° TRAMITE</th>
        <th>TITULO DE TESIS</th>
        <th>ESTUDIANTE</th>
        <th>ESTADO</th>
        <th></th>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>