<div class="tab-content clearfix">
    <div class="form-horizontal">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#estudiante" data-toggle="tab"> DATOS DE ESTUDIANTE</a></li>
            <li><a href="#esquema" data-toggle="tab"> DATOS DE ESQUEMA</a></li>
        </ul>
        <form class="tab-content clearfix" method="post">
            <div class="tab-pane active" id="estudiante">
                <br>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Código</label>
                        <div class="col-lg-3">
                            <div class="input-group">
                                <input class="form-control" type="text" name="codigo">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="button"><i class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </div>
                        <label class="col-lg-2 control-label">DNI</label>
                        <div class="col-lg-3">
                            <input class="form-control" type="text" name="dni" readonly>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Nombres</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="nombres" readonly>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Ap. Paterno</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="ape_pat" readonly>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Ap. Materno</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="ape_mat" readonly>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Fecha Nac.</label>
                        <div class="col-lg-3">
                            <input type="date" class="form-control" readonly />
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">N° Tramite</label>
                        <div class="col-lg-3">
                            <div class="input-group">
                                <input type="text" class="form-control" />
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="button"><i class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pull-right">
                    <a class="btn btn-info" data-toggle="tab" href="#esquema">Siguiente <i class="glyphicon glyphicon-arrow-right"></i></a>
                </div>
            </div>
            <div class="tab-pane" id="esquema">
                <br>
                <div class="form-group">
                    <label class="col-lg-2 control-label">Titulo de Tesis</label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" placeholder="Ingrese titulo de tesis" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">Palabras clave</label>
                    <div class="col-lg-10">
                        <textarea class="form-control"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">Objetivos Principales</label>
                    <div class="col-lg-10">
                        <textarea class="form-control"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">Objetivos Secundarios</label>
                    <div class="col-lg-10">
                        <textarea class="form-control"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">EStado</label>
                    <div class="col-lg-3">
                        <input type="text" class="form-control" value="PRESENTADO" />
                    </div>
                </div>
                <div class="pull-right">
                    <a href="#estudiante" data-toggle="tab" class="btn btn-info"><i class="glyphicon glyphicon-arrow-left"></i> Atras</a>
                    <button class="btn btn-success"><i class="glyphicon glyphicon-saved"></i> GUARDAR</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $('#myTab a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    })
</script>