<div class="page-header">
    <h3>Asesores</h3>
</div>
<div class="row-fluid">
    <div class="control-group">
        <div class="btn-group">
            <a href="<?= $this->url('asesor',array('action'=>'nuevo'))?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> NUEVO</a>
            <a href="#" class="btn btn-warning"><i class="glyphicon glyphicon-th"></i> GENERAR REPORTE</a>
        </div>
    </div>
</div>
<div class="form-horizontal">
    <div class="control-group">
        <form class="span7">
            <div class="input-prepend input-append">
                <div class="add-on">Nombre de Asesor</div>
                <input type="text" name="q" class="form-control"/>
                <button class="btn btn-default"><i class="icon-search"></i></button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">LISTA DE ASESORES</h2>
        </div>
        <table id="asesor" class="panel-body table table-bordered table-striped table-condensed">
            <thead>
            <th>N° ASESORIA</th>
            <th>CODIGO DOCENTE</th>
            <th>NOMBRE DOCENTE</th>
            <th>APELLIDO MATERNO</th>
            <th>APELLIDO PATERNO</th>
            </thead>
            <tbody>
            <?php foreach ($asesor as $ase):?>
                <tr>
                    <td><?=$ase['asesoria_id']?></td>
                    <td><?=$ase['doc_codigo']?></td>
                    <td><?=$ase['per_nombre']?></td>
                    <td><?=$ase['per_ape_mat']?></td>
                    <td><?=$ase['per_ape_pat']?></td>
                    <td>
                        <a href="<?=$this->url('asesor',['action' => 'editar', 'key' => $ase['asesoria_id']])?>" class="btn btn-info btn-inverse"><i class="icon-edit"></i></a>
                    </td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>