<div class="page-header">
    <h3>Asesores</h3>
</div>
<div class="row-fluid">
    <div class="control-group">
        <div class="btn-group">
            <a href="<?= $this->url('asesor',array('action'=>'nuevo'))?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> NUEVO</a>
            <a href="#" class="btn btn-warning"><i class="glyphicon glyphicon-th"></i> GENERAR REPORTE</a>
        </div>
    </div>
</div>
<div class="form-horizontal">
    <div class="control-group">
        <form class="span7">
            <div class="input-prepend input-append">
                <div class="add-on">Nombre de Asesor</div>
                <input type="text" name="q" class="form-control"/>
                <button class="btn btn-default"><i class="icon-search"></i></button>
            </div>
        </form>
    </div>
</div>
<div class="row-fluid panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">Resultados</h4>
    </div>
    <table class="panel-body table table-bordered table-hover">
        <thead>
        <th>#</th>
        <th>CÓDIGO ASESORIA</th>
        <th>CÓDIGO DOCENTE</th>
        <th>ESTADO</th>
        <th>INFORME</th>
        <th></th>
        <tbody>
        <?php foreach ($asesor as $ase):?>
            <tr>
                <td><?=$ase['asesoria_id']?></td>
                <td><?=$ase['doc_codigo']?></td>
                <td><?=$ase['estado_informe']?></td>
                <td><?=$ase['tram_id']?></td>
                <td>
                    <a href="<?=$this->url('asesor',['action' => 'editar', 'key' => $ase['doc_codigo']])?>" class="btn btn-info btn-inverse"><i class="icon-edit"></i></a>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>
</div>