<div class="row-fluid">
    <table id="tbAsesoria" class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th>CODIGO</th>
            <th>CODIGO DOCENTE</th>
            <th>NOMBRE DOCENTE</th>
            <th>APELLIDO PATERNO</th>
            <th>APELLIDO MATERNO</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($asesoria as $item):?>

            <tr>
                <td><?=$this->escapeHtml($item['asesoria_id'])?></td>
                <td><?=$this->escapeHtml($item['doc_codigo'])?></td>
                <td><?=$this->escapeHtml($item['per_nombre'])?></td>
                <td><?=$this->escapeHtml($item['per_ape_pat'])?></td>
                <td><?=$this->escapeHtml($item['per_ape_mat'])?></td>
                <td>
                    <button data-role="close-modal" data-action="Asesoria.elegir('<?=$item['asesoria_id']?>','<?=$item['per_nombre']?>')" class="btn btn-primary"><i class="icon-check"></i></button>
                </td>
            </tr>

        <?php endforeach;?>

        </tbody>
    </table>
</div>
