<form class="form-horizontal" role="form" method="post">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#asesor" data-toggle="tab" >Datos de Docente</a></li>
        <li><a href="#asesorados" data-toggle="tab">Asesorados</a></li>
    </ul>
    <div class="tab-content">
        <br>
        <div class="tab-pane active" id="asesor">
            <div class="span9">
                <div class="control-group">
                    <label class="control-label">Código</label>
                    <div class="controls">
                        <input readonly class="form-control" type="text" name="codigo">
                        <button data-style="modal-lg" data-role="modal-async" data-href="<?=$this->url('docente', [ 'action' => 'mbuscar' ])?>" data-icon="icon-search" data-title="Buscar Docente" class="btn btn-info" type="button"><i class="icon-search"></i></button>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Nombres</label>
                    <div class="controls">
                        <input type="text" class="form-control size-y" name="nombre" readonly>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Ap. Paterno</label>
                    <div class="controls">
                        <input type="text" class="form-control size-y" name="apepat" readonly>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Ap. Materno</label>
                    <div class="controls">
                        <input type="text" class="form-control size-y" name="apemat" readonly>
                    </div>
                </div>
                <div class="form-group pull-right">
                    <a href="#asesorados" data-toggle="tab" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> AGREGAR ASESORADO</a>
                    <button class="btn btn-primary"><i class="glyphicon glyphicon-saved"></i> GUARDAR</button>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="asesorados">
            <div class="span12">
                <div class="control-group">
                    <div class="btn-group">
                        <button class="btn btn-success"><i class="icon-plus"></i></button>
                        <button class="btn btn-danger"><i class="icon-remove"></i></button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</form>
<script src="<?=$this->basePath('plugins/Docente.js')?>"></script>