<div class="row-fluid">
    <div class="control-group">
        <div class="btn-group">
            <a href="<?= $this->url('usuario',array('action'=>'nuevo')) ?>" class="btn btn-success"><i class="icon-plus"></i> NUEVO</a>
            <a href="#" class="btn btn-warning"><i class="icon-th"></i> GENERAR REPORTE</a>
        </div>
    </div>
    <br>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>USUARIO</th>
                <th>NOMBRE</th>
                <th>TIPO</th>
                <th>ESTADO</th>
                <th>OPCIONES</th>
            </tr>
            </thead>
            <tbody>
           <?php foreach ($usuarios as $usuario):?>
                <tr>
                    <td><?= $this->escapeHtml($usuario['usu_id']) ?></td>
                    <td><?= $this->escapeHtml($usuario['usu_login']) ?></td>
                    <td><?= $this->escapeHtml($usuario['nombres']) ?></td>
                    <td><?= $this->escapeHtml($usuario['tipo_usu_nombre']) ?></td>
                    <td><?= $this->escapeHtml($usuario['usu_estado']) ?></td>
                    <td class="center">
                        <div class="btn-group">
                            <button data-title="Usuario #<?=$usuario['usu_id']?>" data-role="modal-async" data-style="modal-lg" data-icon="halflings-icon eye-open" data-href="<?= $this->url('usuario', ['action'=>'ver','id'=>$usuario['usu_id']])?>" class="btn btn-info"><i class="halflings-icon eye-open white"></i></button>
                            <?php
                            if($usuario['tipo_usu_nombre']!='ADMINISTRADOR'){
                                ?>
                                <a href="<?= $this->url('usuario', ['action'=>'editar','id'=>$usuario['usu_id']])?>" class="btn btn-success"><i class="icon-edit"></i></a>
                                <?php
                            }
                            ?>
                        </div>
                    </td>
                </tr>
            <?endforeach;?>
            </tbody>
        </table>
    </div>
</div>
