<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="<?=$this->url('home')?>">Inicio</a>
        <i class="icon-angle-right"></i>
    </li>
    <li>
        <a href="#" class="disabled">Nuevo Usuario</a>
    </li>
</ul>
<div class="row-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">NUEVO USUARIO</h2>
        </div>
    </div>
    <div class="panel-body">
        <form method="post" class="form-horizontal">
            <div class="control-group">
                <label class="control-label">USUARIO</label>
                <div class="controls">
                    
                </div>
            </div>
        </form>
    </div>
</div>