<div class="container-fluid-full bg-metro">
    <div class="row-fluid">

        <div class="row-fluid">
            <div class="login-box">
                <div class="icons">
                    <a href="<?=$this->url('home')?>"><i class="halflings-icon home"></i></a>
                    <a href="#"><i class="halflings-icon cog"></i></a>
                </div>
                <h2>Control de Tesis</h2>
                <form class="form-horizontal" method="post">
                    <fieldset>

                        <div class="input-prepend" title="Nombre de usuario">
                            <span class="add-on"><i class="halflings-icon user"></i></span>
                            <input class="input-large span10" name="username" id="username" type="text" placeholder="nombre de usuario">
                        </div>
                        <div class="clearfix"></div>

                        <div class="input-prepend" title="Contraseña">
                            <span class="add-on"><i class="halflings-icon lock"></i></span>
                            <input class="input-large span10" name="password" id="password" type="password" placeholder="ingrese contraseña">
                        </div>
                        <div class="clearfix"></div>

                        <label class="remember" for="remember"><div class="checker" id="uniform-remember"><span><input type="checkbox" id="remember"></span></div>Recordarme</label>

                        <div class="button-login">
                            <button type="submit" class="btn btn-primary">Iniciar Sessión</button>
                        </div>
                        <div class="clearfix"></div>

                        <hr>
                        <h3>¿Olvidaste tu Contraseña?</h3>
                        <p>
                            No hay problema, haga <a href="<?=$this->url('auth',['action'=>'recuperar'])?>">click aquí</a> para obtener una nueva contraseña.
                        </p>
                    </fieldset></form></div>
        </div>
    </div>

</div>