<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->title)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])?>

        <link id="bootstrap-style" href="<?=$this->basePath('css/bootstrap.min.css')?>" rel="stylesheet">
        <link href="<?=$this->basePath('css/bootstrap-responsive.min.css')?>" rel="stylesheet">
        <link id="base-style" href="<?=$this->basePath('css/style.css')?>" rel="stylesheet">
        <link id="base-style-responsive" href="<?=$this->basePath('css/style-responsive.css')?>" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'>
        <!-- end: CSS -->


        <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <link id="ie-style" href="<?=$this->basePath('css/ie.css')?>" rel="stylesheet">
        <![endif]-->

        <!--[if IE 9]>
            <link id="ie9style" href="css/ie9.css" rel="stylesheet">

            <!-- Scripts -->
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?=$this->url('home')?>"><span>Sistema Control de Tesis</span></a>

                    <div class="nav-no-collapse header-nav">
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="halflings-icon white user"></i> <?=$_SESSION[SESSION_NAME]?>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-menu-title">
                                        <span>Ajustes de Cuenta</span>
                                    </li>
                                    <li><a href="#"><i class="halflings-icon user"></i> Perfil</a></li>
                                    <li><a href="<?=$this->url('auth', ['action'=>'logout'])?>"><i class="halflings-icon off"></i> Cerrar Sessión</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>

        <div class="container-fluid-full" style="margin-top:40px;">
            <div class="row-fluid">

                <div id="sidebar-left" class="span2">
                    <div class="nav-collapse sidebar-nav">
                        <ul class="nav nav-tabs nav-stacked main-menu">
                            <li><a href="<?=$this->url('esquema')?>"><i class="icon-bar-chart"></i><span class="hidden-tablet"> Esquemas</span></a></li>
                            <li><a href="<?=$this->url('asesor')?>"><i class="icon-user"></i><span class="hidden-tablet"> Asesores</span></a></li>
                            <li><a href="#"><i class="icon-legal"></i><span class="hidden-tablet"> Jurado</span></a></li>
                            <li><a href="#"><i class="icon-book"></i><span class="hidden-tablet"> Tesis</span></a></li>
                            <li><a href="<?=$this->url('programacion')?>"><i class="icon-calendar"></i><span class="hidden-tablet"> Programación</span></a></li>
                            <li><a href="<?=$this->url('usuario')?>"><i class="icon-group"></i><span class="hidden-tablet"> Usuarios</span></a></li>
                        </ul>
                    </div>
                </div>

                <div id="content" class="span10">
                    <?=$this->content?>
                </div>

            </div>
        </div>

        <div class="clearfix"></div>
        <footer>
            <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
        </footer>
        
        <script src="<?=$this->basePath('js/jquery-1.9.1.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery-migrate-1.0.0.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery-ui-1.10.0.custom.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.ui.touch-punch.js')?>"></script>
        <script src="<?=$this->basePath('js/modernizr.js')?>"></script>
        <script src="<?=$this->basePath('js/bootstrap.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.cookie.js')?>"></script>
        <script src='<?=$this->basePath('js/fullcalendar.min.js')?>'></script>
        <script src='<?=$this->basePath('js/jquery.dataTables.min.js')?>'></script>
        <script src="<?=$this->basePath('js/excanvas.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.flot.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.flot.pie.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.flot.stack.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.flot.resize.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.chosen.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.uniform.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.cleditor.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.noty.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.elfinder.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.raty.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.iphone.toggle.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.uploadify-3.1.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.gritter.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.imagesloaded.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.masonry.min.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.knob.modified.js')?>"></script>
        <script src="<?=$this->basePath('js/jquery.sparkline.min.js')?>"></script>
        <script src="<?=$this->basePath('js/counter.js')?>"></script>
        <script src="<?=$this->basePath('js/retina.js')?>"></script>
        <script src="<?=$this->basePath('js/custom.js')?>"></script>

        <script src="<?=$this->basePath('js/tnqSoft.js')?>"></script>
        <script src="<?=$this->basePath('js/modal.TnqSoft.js')?>"></script>

        <?= $this->inlineScript() ?>
        <script>
            $(document).ready(function () {
               Pagination();
            });
            function Pagination() {
                <?php if(defined('PAGINATION_PAGES')){?>
                var page = parseInt(TNQSOFT.getParameterByName('pag'));
                if(!page){ page = 1; }
                var location = window.location.href;
                var baseUrl = location.substring(0, location.indexOf('?'));
                $('#title-pages').html('Página '+page+' de <?=PAGINATION_PAGES?>');
                $('#pagination').on('change', function () {
                    var value = $(this).val();
                    window.location.href = baseUrl+'?pag='+value;
                });
                $('#pagination').val(page);
                <?php };?>

            }
        </script>
    </body>
</html>
