<ul class="breadcrumb">
    <li>
        <i class="icon-bar-chart"></i>
        <a href="<?=$this->url('esquema')?>">Esquemas</a>
        <i class="icon-angle-right"></i>
    </li>
    <li>
        <a href="#" class="disabled">Editar</a>
    </li>
</ul>
<div class="tab-content clearfix">
    <div class="form-horizontal">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#estudiante" data-toggle="tab"> DATOS DE ESTUDIANTE</a></li>
            <li><a href="#esquema" data-toggle="tab"> DATOS DE ESQUEMA</a></li>
        </ul>
        <form class="tab-content clearfix" method="post">
            <div class="tab-pane active" id="estudiante">
                <div class="span9">
                    <div class="control-group">
                        <label class="control-label">Código</label>
                        <div class="controls">
                            <input class="form-control" type="text" name="codigo" value="<?=$this->escapeHtml($esquema['est_codigo'])?>">
                            <button data-style="modal-lg" data-role="modal-async" data-href="<?=$this->url('estudiante', [ 'action' => 'mbuscar' ])?>" data-icon="icon-search" data-title="Buscar Estudiante" class="btn btn-default" type="button"><i class="icon-search"></i></button>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">DNI</label>
                        <div class="controls">
                            <input class="form-control" type="text" name="dni" value="<?=$this->escapeHtml($esquema['per_dni'])?>" readonly>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Nombres</label>
                        <div class="controls">
                            <input type="text" class="form-control size-y" name="nombres" value="<?=$this->escapeHtml($esquema['per_nombre'])?>" readonly>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Ap. Paterno</label>
                        <div class="controls">
                            <input type="text" class="form-control size-y" name="ape_pat" value="<?=$this->escapeHtml($esquema['per_ape_pat'])?>" readonly>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Ap. Materno</label>
                        <div class="controls">
                            <input type="text" class="form-control size-y"  value="<?=$this->escapeHtml($esquema['per_ape_mat'])?>" name="ape_mat" readonly>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Fecha Nac.</label>
                        <div class="controls">
                            <input type="date" class="form-control" name="fechaNac" readonly  value="<?=$this->escapeHtml($esquema['per_fecha_nac'])?>" />
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">N° Tramite</label>
                        <div class="controls">
                            <div class="input-prepend input-append">
                                <input type="text" class="form-control" name="nroTramite"  value="<?=$this->escapeHtml($esquema['tram_id'])?>" />
                                <button class="btn btn-default" type="button"><i class="icon-search"></i></button>
                            </div>
                        </div>
                    </div>
                    <div class="control-group pull-right">
                        <a class="btn btn-info" data-toggle="tab" href="#esquema">Siguiente <i class="icon-arrow-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="tab-pane center" id="esquema">
                <div class="span7">
                    <input type="hidden" value="<?=$this->escapeHtml($esquema['tram_id'])?>">
                    <div class="control-group">
                        <label class="control-label">Titulo de Tesis</label>
                        <div class="controls">
                            <input type="text" name="tituloTesis" value="<?=$this->escapeHtml($esquema['titulo_tesis'])?>" class="form-control size-y" placeholder="Ingrese titulo de tesis" />
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Palabras clave</label>
                        <div class="controls">
                            <textarea name="palabrasClaves" class="form-control size-y"><?=$this->escapeHtml($esquema['keyswords'])?></textarea>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Objetivos Principales</label>
                        <div class="controls">
                            <textarea name="objPrincipales" class="cleditor size-y"><?=$this->escapeHtml($esquema['obj_pri'])?></textarea>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Objetivos Secundarios</label>
                        <div class="controls">
                            <textarea name="objSecundarios" class="cleditor size-y"><?=$this->escapeHtml($esquema['obj_sec'])?></textarea>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">EStado</label>
                        <div class="controls">
                            <input type="text" name="estado" readonly class="form-control size-y" value="<?=$this->escapeHtml($esquema['esq_estado'])?>" />
                        </div>
                    </div>
                    <div class="control-group">
                        <button class="btn btn-success"><i class="icon-saved"></i> GUARDAR</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="<?=$this->basePath('plugins/estudiante.TnqSoft.js')?>"></script>