<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="<?=$this->url('home')?>">Inicio</a>
    </li>
</ul>
<div class="row-fluid">
    <div class="span12">
        <div class="form-group">
            <div class="btn-group">
                <a href="<?= $this->url('esquema',array('action'=>'nuevo'))?>" class="btn btn-success"><i class="icon-plus"></i> NUEVO</a>
                <a href="#" class="btn btn-warning"><i class="icon-th"></i> GENERAR REPORTE</a>
            </div>
        </div>
        <br>
    </div>
</div>
<div class="row-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">LISTA DE ESQUEMAS</h2>
        </div>
        <table id="esquemas" class="panel-body table table-bordered table-striped table-condensed">
            <thead>
            <th>N° TRAMITE</th>
            <th>TITULO DE TESIS</th>
            <th>CODIGO ESTUDIANTE</th>
            <th>ESTUDIANTE</th>
            <th>ESTADO</th>
            <th></th>
            </thead>
            <tbody>
            <?php foreach ($esquemas as $esq):?>
                <tr>
                    <td><?=$esq['tram_id']?></td>
                    <td><?=$esq['titulo_tesis']?></td>
                    <td><?=$esq['est_codigo']?></td>
                    <td><?=sprintf("%s %s %s",$esq['per_nombre'], $esq['per_ape_pat'], $esq['per_ape_mat'])?></td>
                    <td><?=$esq['esq_estado']?></td>
                    <td>
                        <a href="<?=$this->url('esquema',['action' => 'editar', 'key' => $esq['tram_id']])?>" class="btn btn-info btn-inverse"><i class="icon-edit"></i></a>
                    </td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>