<div class="row-fluid">
    <table id="tbEvaluacion" class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th>CODIGO</th>
            <th>#TRAMITE</th>
            <th>FECHA REGISTRO</th>
            <th>TIPO</th>
            <th>ESTADO</th>
            <th>DESCRIPCION</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($evaluacion as $item):?>

            <tr>
                <td><?=$this->escapeHtml($item['eva_id'])?></td>
                <td><?=$this->escapeHtml($item['tram_id'])?></td>
                <td><?=$this->escapeHtml($item['eva_fecha_erg'])?></td>
                <td><?=$this->escapeHtml($item['tipo_evaluacion'])?></td>
                <td><?=$this->escapeHtml($item['eva_estado'])?></td>
                <td><?=$this->escapeHtml($item['eva_descripcion'])?></td>
                <td>
                    <button data-role="close-modal" data-action="Evaluacion.elegir('<?=$item['eva_id']?>','<?=$item['eva_estado']?>')" class="btn btn-primary"><i class="icon-check"></i></button>
                </td>
            </tr>

        <?php endforeach;?>

        </tbody>
    </table>
</div>
